"""Decision model — human decision requests and resolutions during execution."""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class DecisionRequest:
    """A structured request for human input during plan execution.

    Created by the execution engine when it encounters an approval gate
    or an agent escalation that requires a human decision.  Surfaced
    via ``baton decide`` or the PMO dashboard.

    Attributes:
        request_id: Unique identifier (auto-generated by ``create()``).
        task_id: Execution this decision belongs to.
        decision_type: Category — ``"gate_approval"``, ``"escalation"``,
            or ``"plan_review"``.
        summary: Human-readable description of what needs deciding.
        options: Available choices (e.g. ``["approve", "reject"]``).
        deadline: Optional ISO 8601 timeout after which a default
            applies.
        context_files: Paths to files relevant to the decision.
        created_at: ISO 8601 creation timestamp.
        status: Lifecycle state — ``"pending"``, ``"resolved"``, or
            ``"expired"``.
    """

    request_id: str
    task_id: str
    decision_type: str       # "gate_approval", "escalation", "plan_review"
    summary: str             # human-readable context
    options: list[str] = field(default_factory=list)  # e.g. ["approve", "reject", "modify"]
    deadline: str | None = None  # ISO 8601 timeout (optional)
    context_files: list[str] = field(default_factory=list)
    created_at: str = ""
    status: str = "pending"  # "pending", "resolved", "expired"

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    @classmethod
    def create(
        cls,
        task_id: str,
        decision_type: str,
        summary: str,
        options: list[str] | None = None,
        **kwargs: object,
    ) -> DecisionRequest:
        """Factory method — auto-generates a request_id."""
        return cls(
            request_id=uuid.uuid4().hex[:12],
            task_id=task_id,
            decision_type=decision_type,
            summary=summary,
            options=options or ["approve", "reject"],
            **kwargs,  # type: ignore[arg-type]
        )

    def to_dict(self) -> dict:
        return {
            "request_id": self.request_id,
            "task_id": self.task_id,
            "decision_type": self.decision_type,
            "summary": self.summary,
            "options": self.options,
            "deadline": self.deadline,
            "context_files": self.context_files,
            "created_at": self.created_at,
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, data: dict) -> DecisionRequest:
        return cls(
            request_id=data.get("request_id", ""),
            task_id=data.get("task_id", ""),
            decision_type=data.get("decision_type", ""),
            summary=data.get("summary", ""),
            options=data.get("options", []),
            deadline=data.get("deadline"),
            context_files=data.get("context_files", []),
            created_at=data.get("created_at", ""),
            status=data.get("status", "pending"),
        )


@dataclass
class DecisionResolution:
    """The recorded outcome of a resolved ``DecisionRequest``.

    Created when a human (or an auto-policy) selects one of the
    request's options.  Persisted alongside the request for audit
    trail purposes.

    Attributes:
        request_id: The ``DecisionRequest.request_id`` this resolves.
        chosen_option: The option selected from the request's choices.
        rationale: Optional explanation for the decision.
        resolved_by: Who resolved it — ``"human"``,
            ``"timeout_default"``, or ``"auto_policy"``.
        resolved_at: ISO 8601 timestamp of resolution.
    """

    request_id: str
    chosen_option: str
    rationale: str | None = None
    resolved_by: str = "human"  # "human", "timeout_default", "auto_policy"
    resolved_at: str = ""

    def __post_init__(self) -> None:
        if not self.resolved_at:
            self.resolved_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "request_id": self.request_id,
            "chosen_option": self.chosen_option,
            "rationale": self.rationale,
            "resolved_by": self.resolved_by,
            "resolved_at": self.resolved_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> DecisionResolution:
        return cls(
            request_id=data.get("request_id", ""),
            chosen_option=data.get("chosen_option", ""),
            rationale=data.get("rationale"),
            resolved_by=data.get("resolved_by", "human"),
            resolved_at=data.get("resolved_at", ""),
        )


@dataclass
class ContributionRequest:
    """Open-ended request for input from multiple participants.

    Unlike DecisionRequest (binary choice), ContributionRequest stays
    open until all named contributors respond or a deadline expires.
    A facilitator agent synthesizes when all inputs arrive.

    Attributes:
        request_id: Unique identifier.
        task_id: Execution this contribution belongs to.
        topic: What input is being requested.
        description: Detailed context for contributors.
        contributors: Named participants expected to contribute.
        responses: Mapping of contributor name to their input.
        facilitator_agent: Agent that synthesizes when all inputs arrive.
        deadline: ISO 8601 deadline (optional).
        created_at: ISO 8601 creation time.
        status: "collecting", "ready", "synthesized", "expired".
    """

    request_id: str
    task_id: str
    topic: str
    description: str = ""
    contributors: list[str] = field(default_factory=list)
    responses: dict[str, str] = field(default_factory=dict)
    facilitator_agent: str = "architect"
    deadline: str | None = None
    created_at: str = ""
    status: str = "collecting"  # collecting | ready | synthesized | expired

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")

    @property
    def is_complete(self) -> bool:
        """True when all expected contributors have responded."""
        return all(c in self.responses for c in self.contributors)

    @property
    def pending_contributors(self) -> list[str]:
        """Contributors who haven't responded yet."""
        return [c for c in self.contributors if c not in self.responses]

    def respond(self, contributor: str, response: str) -> None:
        """Record a contributor's response. Updates status to 'ready' when all have responded."""
        self.responses[contributor] = response
        if self.is_complete:
            self.status = "ready"

    def to_dict(self) -> dict:
        return {
            "request_id": self.request_id,
            "task_id": self.task_id,
            "topic": self.topic,
            "description": self.description,
            "contributors": self.contributors,
            "responses": self.responses,
            "facilitator_agent": self.facilitator_agent,
            "deadline": self.deadline,
            "created_at": self.created_at,
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ContributionRequest:
        return cls(
            request_id=data.get("request_id", ""),
            task_id=data.get("task_id", ""),
            topic=data.get("topic", ""),
            description=data.get("description", ""),
            contributors=data.get("contributors", []),
            responses=data.get("responses", {}),
            facilitator_agent=data.get("facilitator_agent", "architect"),
            deadline=data.get("deadline"),
            created_at=data.get("created_at", ""),
            status=data.get("status", "collecting"),
        )
