"""Execution engine models — machine-readable plans, state, and actions.

This module defines the core data structures that flow through the
execution engine: the plan hierarchy (``MachinePlan`` > ``PlanPhase`` >
``PlanStep``), the persistent ``ExecutionState`` saved between CLI calls,
result records (``StepResult``, ``GateResult``, ``ApprovalResult``), and
the ``ExecutionAction`` instructions returned to the driving session.

These models are the contract between the planner, executor, and CLI.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from agent_baton.models.knowledge import (
    KnowledgeAttachment,
    KnowledgeGapSignal,
    ResolvedDecision,
)
from agent_baton.models.parallel import ResourceLimits
from agent_baton.models.taxonomy import ForesightInsight

# Matches team-member IDs of the form N.N.x and nested forms N.N.x.y...
# (e.g. "1.1.a", "2.3.b", "1.1.a.b" for nested sub-team members).
# Used in ExecutionAction.to_dict() to set the is_team_member flag.
_TEAM_MEMBER_ID_RE = re.compile(r'^\d+\.\d+(?:\.[a-z]+)+$')


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class StepStatus(Enum):
    """Lifecycle state of a single plan step."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    FAILED = "failed"
    SKIPPED = "skipped"
    INTERRUPTED = "interrupted"
    INTERACTING = "interacting"              # agent responded, awaiting human input
    INTERACT_DISPATCHED = "interact_dispatched"  # human input given, agent re-dispatched


class PhaseStatus(Enum):
    """Lifecycle state of a plan phase."""

    PENDING = "pending"
    RUNNING = "running"
    GATE_PENDING = "gate_pending"
    COMPLETE = "complete"
    FAILED = "failed"


class ActionType(Enum):
    """What the caller (Claude session) should do next."""
    DISPATCH = "dispatch"               # spawn a subagent with the given prompt
    GATE = "gate"                       # run a QA gate check
    COMPLETE = "complete"               # execution is finished
    FAILED = "failed"                   # execution cannot continue
    WAIT = "wait"                       # parallel steps still running
    APPROVAL = "approval"               # pause for human review / approval
    FEEDBACK = "feedback"               # present multiple-choice questions, dispatch based on answers
    INTERACT = "interact"               # multi-turn interaction: agent responded, awaiting human input
    SWARM_DISPATCH = "swarm.dispatch"   # Wave 6.2 (bd-2b9f): trigger a SwarmDispatcher run
    CHECKPOINT = "checkpoint"            # save state + suggest fresh session to prevent context rot


# ---------------------------------------------------------------------------
# Interaction history (multi-turn step conversations)
# ---------------------------------------------------------------------------

@dataclass
class InteractionTurn:
    """A single turn in a multi-turn agent interaction.

    Recorded in :class:`StepResult.interaction_history` for interactive steps
    that use the INTERACT protocol.  Each turn is either an agent response or
    human input.

    Attributes:
        role: Either ``"agent"`` (step output) or ``"human"`` (orchestrator
            input via ``baton execute interact``).
        content: The text of this turn.
        timestamp: ISO 8601 timestamp, auto-set in ``__post_init__`` when
            not supplied.
        turn_number: Sequential 1-based turn index within the interaction.
        source: Origin of a human-role turn.  One of:

            - ``"human"`` — typed by a person (CLI or PMO UI).
            - ``"auto-agent"`` — generated by Tier A daemon auto-resolution.
            - ``"webhook"`` — received via external webhook response.

            Agent-role turns always have source ``"agent"`` (same as role).
            Defaults to ``"human"`` so existing states deserialise correctly.
    """

    role: str                   # "agent" or "human"
    content: str
    timestamp: str = ""
    turn_number: int = 0
    source: str = "human"       # "human" | "auto-agent" | "webhook"

    def __post_init__(self) -> None:
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "role": self.role,
            "content": self.content,
            "timestamp": self.timestamp,
            "turn_number": self.turn_number,
            "source": self.source,
        }

    @classmethod
    def from_dict(cls, data: dict) -> InteractionTurn:
        return cls(
            role=data.get("role", "agent"),
            content=data.get("content", ""),
            timestamp=data.get("timestamp", ""),
            turn_number=data.get("turn_number", 0),
            source=data.get("source", "human"),
        )


# ---------------------------------------------------------------------------
# Plan (machine-readable, JSON-serializable)
# ---------------------------------------------------------------------------

@dataclass
class TeamMember:
    """A member of a coordinated agent team within a step.

    Team steps allow multiple agents to collaborate on a single step,
    with intra-step dependency ordering.  Each member is dispatched
    individually and results are collected via ``TeamStepResult``.

    Attributes:
        member_id: Hierarchical ID (e.g. ``"1.1.a"``).
        agent_name: Name of the agent assigned to this role.
        role: Function within the team — ``"lead"``, ``"implementer"``,
            or ``"reviewer"``.
        task_description: What this team member should do.
        model: LLM model to use.
        depends_on: Other ``member_id`` values that must complete first.
        deliverables: Expected output artifacts.
        sub_team: Nested team the lead coordinates.  Non-empty only when
            ``role == "lead"``; enforced by :meth:`validate`.  The lead is
            still dispatched as a worker — its own outcome is merged with
            sub-team outcomes by the enclosing step's ``synthesis``.
        synthesis: How the lead's own outcome is merged with sub-team
            outcomes.  Meaningful only when ``sub_team`` is non-empty.
    """

    member_id: str                          # e.g. "1.1.a"
    agent_name: str
    role: str = "implementer"               # "lead", "implementer", "reviewer"
    task_description: str = ""
    model: str = "sonnet"
    depends_on: list[str] = field(default_factory=list)   # other member_ids
    deliverables: list[str] = field(default_factory=list)
    sub_team: list[TeamMember] = field(default_factory=list)  # nested team
    synthesis: SynthesisSpec | None = None  # merge strategy iff sub_team non-empty

    def validate(self) -> None:
        """Raise ``ValueError`` when the member carries a ``sub_team`` but is
        not a lead.  Sub-teams may only be attached to ``role == "lead"``."""
        if self.sub_team and self.role != "lead":
            raise ValueError(
                f"TeamMember {self.member_id!r} has a sub_team but role={self.role!r}; "
                "only role='lead' members may carry a sub_team."
            )

    def to_dict(self) -> dict:
        d: dict = {
            "member_id": self.member_id,
            "agent_name": self.agent_name,
            "role": self.role,
            "task_description": self.task_description,
            "model": self.model,
            "depends_on": self.depends_on,
            "deliverables": self.deliverables,
        }
        if self.sub_team:
            d["sub_team"] = [m.to_dict() for m in self.sub_team]
        if self.synthesis is not None:
            d["synthesis"] = self.synthesis.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: dict) -> TeamMember:
        synth_data = data.get("synthesis")
        return cls(
            member_id=data["member_id"],
            agent_name=data["agent_name"],
            role=data.get("role", "implementer"),
            task_description=data.get("task_description", ""),
            model=data.get("model", "sonnet"),
            depends_on=data.get("depends_on", []),
            deliverables=data.get("deliverables", []),
            sub_team=[cls.from_dict(m) for m in data.get("sub_team", [])],
            synthesis=SynthesisSpec.from_dict(synth_data) if synth_data else None,
        )


@dataclass
class SynthesisSpec:
    """Configuration for how team member outputs are combined.

    Attached to a :class:`PlanStep` to control how the engine merges
    results when all team members complete.

    Attributes:
        strategy: How outputs are combined:
            - ``"concatenate"`` — join outcomes with ``"; "`` (default,
              backward-compatible).
            - ``"merge_files"`` — collect all ``files_changed`` and
              deduplicate; outcomes concatenated.
            - ``"agent_synthesis"`` — dispatch a synthesis agent to
              merge outputs into a coherent whole.
        synthesis_agent: Agent name for ``agent_synthesis`` strategy.
            Defaults to ``"code-reviewer"`` if unset.
        synthesis_prompt: Optional custom prompt template for the
            synthesis agent.  ``{member_outcomes}`` is replaced with
            the formatted member results.
        conflict_handling: How to handle detected conflicts between
            member outputs:
            - ``"auto_merge"`` — attempt automatic merge (default).
            - ``"escalate"`` — surface conflict to human via APPROVAL
              action with both positions.
            - ``"fail"`` — fail the team step if conflicts detected.
    """

    strategy: str = "concatenate"           # concatenate | merge_files | agent_synthesis
    synthesis_agent: str = "code-reviewer"
    synthesis_prompt: str = ""
    conflict_handling: str = "auto_merge"   # auto_merge | escalate | fail

    def to_dict(self) -> dict:
        return {
            "strategy": self.strategy,
            "synthesis_agent": self.synthesis_agent,
            "synthesis_prompt": self.synthesis_prompt,
            "conflict_handling": self.conflict_handling,
        }

    @classmethod
    def from_dict(cls, data: dict) -> SynthesisSpec:
        return cls(
            strategy=data.get("strategy", "concatenate"),
            synthesis_agent=data.get("synthesis_agent", "code-reviewer"),
            synthesis_prompt=data.get("synthesis_prompt", ""),
            conflict_handling=data.get("conflict_handling", "auto_merge"),
        )


@dataclass
class PlanStep:
    """A single agent assignment within a plan phase.

    Steps are the atomic unit of work dispatched to agents.  They carry
    the task description, path constraints (sandbox), dependency ordering,
    and any knowledge attachments resolved during planning.

    Attributes:
        step_id: Hierarchical ID (e.g. ``"1.1"`` = phase 1, step 1).
        agent_name: Agent to dispatch for this step.
        task_description: What the agent should accomplish.
        model: LLM model to use for this dispatch.
        depends_on: ``step_id`` values that must complete before this step.
        deliverables: Expected output artifacts.
        allowed_paths: Filesystem paths the agent may write to (sandbox).
        blocked_paths: Filesystem paths the agent must not modify.
        context_files: Files the agent should read before starting.
        team: If non-empty, this is a team step with multiple members.
        knowledge: Knowledge documents attached by the planner.
        synthesis: How to merge team member outputs.  Only meaningful
            when ``team`` is non-empty.
        expected_outcome: One-sentence behavioral statement describing what
            should be observably true after this step completes.  Wave 3.1
            (Demo Statement) — used as the primary prompt anchor for
            ``code-reviewer`` and ``test-engineer`` to shift review from
            "no errors" to "behavioral correctness".  Empty string means
            no outcome was derived (preserves back-compat for older plans).
        parallel_safe: Annotated ``True`` by the planner (bd-a379) when this
            step shares its ``depends_on`` set with at least one sibling and
            every such sibling has a disjoint ``allowed_paths`` set.  Defaults
            to ``False`` (conservative — sequential) for any step the planner
            cannot prove is safe to run concurrently.  Orchestrators SHOULD
            dispatch concurrent worktree-isolated agents when this is ``True``.
    """

    step_id: str                          # e.g. "1.1"
    agent_name: str
    task_description: str
    model: str = "sonnet"
    depends_on: list[str] = field(default_factory=list)
    deliverables: list[str] = field(default_factory=list)
    allowed_paths: list[str] = field(default_factory=list)
    blocked_paths: list[str] = field(default_factory=list)
    context_files: list[str] = field(default_factory=list)  # files agent should read
    team: list[TeamMember] = field(default_factory=list)    # non-empty = team step
    knowledge: list[KnowledgeAttachment] = field(default_factory=list)  # resolved knowledge
    synthesis: SynthesisSpec | None = None  # team output merge strategy
    mcp_servers: list[str] = field(default_factory=list)  # MCP server names for this step
    interactive: bool = False       # step uses multi-turn interaction protocol
    max_turns: int = 10             # cost guard: maximum interaction turns
    step_type: str = "developing"   # planning, developing, testing, reviewing,
                                    # consulting, task, automation
    command: str = ""               # shell command for automation steps
    expected_outcome: str = ""      # Wave 3.1: 1-sentence demo statement (behavioral)
    timeout_seconds: int = 0        # 0 = no timeout (backward-compat default)
    parallel_safe: bool = False     # bd-a379: True when sibling steps have disjoint allowed_paths
    max_estimated_minutes: int = 0  # 0 = no estimate; enrichment enforces ceiling

    def to_dict(self) -> dict:
        d = {
            "step_id": self.step_id,
            "agent_name": self.agent_name,
            "task_description": self.task_description,
            "model": self.model,
            "depends_on": self.depends_on,
            "deliverables": self.deliverables,
            "allowed_paths": self.allowed_paths,
            "blocked_paths": self.blocked_paths,
            "context_files": self.context_files,
            "step_type": self.step_type,
        }
        if self.team:
            d["team"] = [m.to_dict() for m in self.team]
        if self.knowledge:
            d["knowledge"] = [k.to_dict() for k in self.knowledge]
        if self.synthesis is not None:
            d["synthesis"] = self.synthesis.to_dict()
        if self.mcp_servers:
            d["mcp_servers"] = self.mcp_servers
        if self.interactive:
            d["interactive"] = self.interactive
            d["max_turns"] = self.max_turns
        if self.command:
            d["command"] = self.command
        if self.expected_outcome:
            d["expected_outcome"] = self.expected_outcome
        if self.timeout_seconds:
            d["timeout_seconds"] = self.timeout_seconds
        if self.parallel_safe:
            d["parallel_safe"] = self.parallel_safe
        if self.max_estimated_minutes:
            d["max_estimated_minutes"] = self.max_estimated_minutes
        return d

    @classmethod
    def from_dict(cls, data: dict) -> PlanStep:
        synthesis_data = data.get("synthesis")
        return cls(
            step_id=data["step_id"],
            agent_name=data["agent_name"],
            task_description=data.get("task_description", ""),
            model=data.get("model", "sonnet"),
            depends_on=data.get("depends_on", []),
            deliverables=data.get("deliverables", []),
            allowed_paths=data.get("allowed_paths", []),
            blocked_paths=data.get("blocked_paths", []),
            context_files=data.get("context_files", []),
            team=[TeamMember.from_dict(m) for m in data.get("team", [])],
            knowledge=[KnowledgeAttachment.from_dict(k) for k in data.get("knowledge", [])],
            synthesis=SynthesisSpec.from_dict(synthesis_data) if synthesis_data else None,
            mcp_servers=data.get("mcp_servers", []),
            interactive=data.get("interactive", False),
            max_turns=data.get("max_turns", 10),
            step_type=data.get("step_type", "developing"),
            command=data.get("command", ""),
            expected_outcome=data.get("expected_outcome", ""),
            timeout_seconds=data.get("timeout_seconds", 0),
            parallel_safe=data.get("parallel_safe", False),
            max_estimated_minutes=data.get("max_estimated_minutes", 0),
        )


@dataclass
class PlanGate:
    """A QA gate that must pass before advancing to the next phase.

    Gates run automated checks (tests, linting, builds) or request
    manual review.  Gate failure triggers the ``GATE`` action in the
    execution loop, giving the orchestrator a chance to re-plan or
    request remediation.

    Attributes:
        gate_type: Category — ``"build"``, ``"test"``, ``"lint"``,
            ``"spec"``, or ``"review"``.
        command: Bash command to run (e.g. ``"pytest"``).
        description: Human-readable explanation of what the gate checks.
        fail_on: Criteria that constitute a failure.
    """

    gate_type: str              # "build", "test", "lint", "spec", "review"
    command: str = ""           # bash command to run (e.g. "pytest")
    description: str = ""
    fail_on: list[str] = field(default_factory=list)  # criteria for failure

    def to_dict(self) -> dict:
        return {
            "gate_type": self.gate_type,
            "command": self.command,
            "description": self.description,
            "fail_on": self.fail_on,
        }

    @classmethod
    def from_dict(cls, data: dict) -> PlanGate:
        # Accept both "gate_type" (canonical) and "type" (common LLM variant)
        gate_type = data.get("gate_type") or data.get("type", "")
        return cls(
            gate_type=gate_type,
            command=data.get("command", ""),
            description=data.get("description", ""),
            fail_on=data.get("fail_on", []),
        )


@dataclass
class PlanPhase:
    """A phase in an execution plan, containing steps and an optional gate.

    Phases group related steps and enforce a gate check or human approval
    before the execution engine advances to the next phase.  The planner
    creates phases based on logical work boundaries and risk thresholds.

    Attributes:
        phase_id: Sequential integer identifier.
        name: Human-readable phase name (e.g. ``"Implementation"``).
        steps: Ordered list of steps to execute in this phase.
        gate: Optional QA gate to run after all steps complete.
        approval_required: If ``True``, pause for human approval after
            steps complete (before the gate, if any).
        approval_description: What the human should review.
        risk_level: Optional per-phase risk override. When non-empty,
            ``ExecutionEngine._enforce_veto_before_advance`` uses this
            tier (LOW|MEDIUM|HIGH|CRITICAL) for VETO gating in place of
            the plan-level value. Lets a CRITICAL plan contain a single
            LOW phase that bypasses VETO blocks (bd-5bd9).
    """

    phase_id: int
    name: str
    steps: list[PlanStep] = field(default_factory=list)
    gate: PlanGate | None = None
    approval_required: bool = False         # pause for human approval after steps complete
    approval_description: str = ""          # what the human should review
    feedback_questions: list[FeedbackQuestion] = field(default_factory=list)  # multiple-choice feedback gate
    risk_level: str = ""                    # bd-5bd9: optional per-phase override

    def to_dict(self) -> dict:
        d: dict = {
            "phase_id": self.phase_id,
            "name": self.name,
            "steps": [s.to_dict() for s in self.steps],
        }
        if self.gate:
            d["gate"] = self.gate.to_dict()
        if self.approval_required:
            d["approval_required"] = self.approval_required
            d["approval_description"] = self.approval_description
        if self.feedback_questions:
            d["feedback_questions"] = [q.to_dict() for q in self.feedback_questions]
        if self.risk_level:
            d["risk_level"] = self.risk_level
        return d

    @classmethod
    def from_dict(cls, data: dict) -> PlanPhase:
        gate = PlanGate.from_dict(data["gate"]) if data.get("gate") else None
        return cls(
            phase_id=data["phase_id"],
            name=data["name"],
            steps=[PlanStep.from_dict(s) for s in data.get("steps", [])],
            gate=gate,
            approval_required=data.get("approval_required", False),
            approval_description=data.get("approval_description", ""),
            feedback_questions=[
                FeedbackQuestion.from_dict(q)
                for q in data.get("feedback_questions", [])
            ],
            risk_level=data.get("risk_level", ""),
        )


@dataclass
class MachinePlan:
    """Machine-readable execution plan — the contract between planner and executor.

    Created by ``IntelligentPlanner.create_plan()`` and persisted as
    ``plan.json``.  The ``ExecutionEngine`` reads this to drive the
    dispatch loop, and ``to_markdown()`` renders it as ``plan.md`` for
    human review.

    Attributes:
        task_id: Unique execution identifier.
        task_summary: Human-readable description of the task.
        risk_level: Classified risk tier (``"LOW"``, ``"MEDIUM"``,
            ``"HIGH"``, ``"CRITICAL"``).
        budget_tier: Token budget allocation (``"lean"``, ``"standard"``,
            ``"full"``).
        execution_mode: Step ordering strategy (``"phased"``,
            ``"parallel"``, ``"sequential"``).
        git_strategy: Version-control approach for agent commits.
        phases: Ordered list of execution phases.
        shared_context: Pre-built context string injected into all
            agent prompts.
        pattern_source: ``pattern_id`` of the learned pattern that
            influenced this plan, if any.
        created_at: ISO 8601 creation timestamp.
        task_type: Inferred task category (e.g. ``"feature"``,
            ``"bug-fix"``).
        explicit_knowledge_packs: Pack names from ``--knowledge-pack``
            CLI flag.
        explicit_knowledge_docs: Document paths from ``--knowledge``
            CLI flag.
        intervention_level: Human intervention frequency —
            ``"low"``, ``"medium"``, or ``"high"``.
        complexity: Plan complexity tier — ``"light"``, ``"medium"``,
            or ``"heavy"``.
        classification_source: How the classification was determined —
            ``"haiku"`` or ``"keyword-fallback"``.
    """

    task_id: str
    task_summary: str
    risk_level: str = "LOW"
    budget_tier: str = "standard"
    execution_mode: str = "phased"
    git_strategy: str = "commit-per-agent"
    phases: list[PlanPhase] = field(default_factory=list)
    shared_context: str = ""            # pre-built context for agents
    pattern_source: str | None = None   # pattern_id that influenced this plan
    created_at: str = ""
    task_type: str | None = None        # inferred task type (e.g. "feature", "bug-fix")
    explicit_knowledge_packs: list[str] = field(default_factory=list)  # from --knowledge-pack
    explicit_knowledge_docs: list[str] = field(default_factory=list)   # from --knowledge
    intervention_level: str = "low"     # low | medium | high
    complexity: str = "medium"          # light | medium | heavy
    classification_source: str = "keyword-fallback"  # haiku | keyword-fallback
    resource_limits: ResourceLimits | None = None  # optional concurrency constraints
    detected_stack: str | None = None  # e.g. "python", "python/react", "typescript/react"
    foresight_insights: list[ForesightInsight] = field(default_factory=list)  # proactive insights
    # E7 — dependency detection: task_id this plan depends on (from prior output)
    depends_on_task: str | None = None
    # A3: persist ClassificationResult signals and confidence alongside the plan.
    # Populated by the planner when a ClassificationResult is available.
    # ``None`` when the classification was performed before this field existed
    # (pre-v10 databases) or when the planner used keyword-fallback only.
    classification_signals: str | None = None    # JSON blob from ClassificationResult.to_dict()
    classification_confidence: float | None = None  # 0.0–1.0 confidence score
    archetype: str = "phased"       # planning archetype: direct | phased | investigative
    max_retry_phases: int = 0       # investigative only: max phase retries before failing

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()

    @property
    def all_steps(self) -> list[PlanStep]:
        return [s for p in self.phases for s in p.steps]

    @property
    def all_agents(self) -> list[str]:
        return [s.agent_name for s in self.all_steps]

    @property
    def total_steps(self) -> int:
        return len(self.all_steps)

    def to_dict(self) -> dict:
        d = {
            "task_id": self.task_id,
            "task_summary": self.task_summary,
            "risk_level": self.risk_level,
            "budget_tier": self.budget_tier,
            "execution_mode": self.execution_mode,
            "git_strategy": self.git_strategy,
            "phases": [p.to_dict() for p in self.phases],
            "shared_context": self.shared_context,
            "pattern_source": self.pattern_source,
            "created_at": self.created_at,
            "task_type": self.task_type,
            "explicit_knowledge_packs": self.explicit_knowledge_packs,
            "explicit_knowledge_docs": self.explicit_knowledge_docs,
            "intervention_level": self.intervention_level,
            "complexity": self.complexity,
            "classification_source": self.classification_source,
            "detected_stack": self.detected_stack,
            "foresight_insights": [i.to_dict() for i in self.foresight_insights],
            "depends_on_task": self.depends_on_task,
            "classification_signals": self.classification_signals,
            "classification_confidence": self.classification_confidence,
            "archetype": self.archetype,
            "max_retry_phases": self.max_retry_phases,
        }
        if self.resource_limits is not None:
            d["resource_limits"] = self.resource_limits.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: dict) -> MachinePlan:
        rl_data = data.get("resource_limits")
        return cls(
            task_id=data["task_id"],
            task_summary=data["task_summary"],
            risk_level=data.get("risk_level", "LOW"),
            budget_tier=data.get("budget_tier", "standard"),
            execution_mode=data.get("execution_mode", "phased"),
            git_strategy=data.get("git_strategy", "commit-per-agent"),
            phases=[PlanPhase.from_dict(p) for p in data.get("phases", [])],
            shared_context=data.get("shared_context", ""),
            pattern_source=data.get("pattern_source"),
            created_at=data.get("created_at", ""),
            task_type=data.get("task_type"),
            explicit_knowledge_packs=data.get("explicit_knowledge_packs", []),
            explicit_knowledge_docs=data.get("explicit_knowledge_docs", []),
            intervention_level=data.get("intervention_level", "low"),
            complexity=data.get("complexity", "medium"),
            classification_source=data.get("classification_source", "keyword-fallback"),
            resource_limits=ResourceLimits.from_dict(rl_data) if rl_data else None,
            detected_stack=data.get("detected_stack"),
            foresight_insights=[
                ForesightInsight.from_dict(i)
                for i in data.get("foresight_insights", [])
            ],
            depends_on_task=data.get("depends_on_task"),
            classification_signals=data.get("classification_signals"),
            classification_confidence=data.get("classification_confidence"),
            archetype=data.get("archetype", "phased"),
            max_retry_phases=data.get("max_retry_phases", 0),
        )

    def to_markdown(self) -> str:
        """Render as human-readable markdown (for plan.md)."""
        lines = [
            "# Execution Plan",
            "",
            f"**Task**: {self.task_summary}",
            f"**Task ID**: {self.task_id}",
            f"**Risk Level**: {self.risk_level}",
            f"**Budget Tier**: {self.budget_tier}",
            f"**Execution Mode**: {self.execution_mode}",
            f"**Git Strategy**: {self.git_strategy}",
            f"**Archetype**: {self.archetype}",
            f"**Created**: {self.created_at}",
        ]
        if self.pattern_source:
            lines.append(f"**Pattern**: {self.pattern_source}")
        if self.task_type:
            lines.append(f"**Task Type**: {self.task_type}")
        if self.intervention_level != "low":
            lines.append(f"**Intervention Level**: {self.intervention_level}")
        lines.append(f"**Complexity**: {self.complexity}")
        lines.append(f"**Classification Source**: {self.classification_source}")
        if self.depends_on_task:
            lines.append(f"**Depends On Task**: {self.depends_on_task}")
        if self.foresight_insights:
            lines.append(f"**Foresight Insights**: {len(self.foresight_insights)} proactive gap(s) addressed")
        if self.explicit_knowledge_packs:
            lines.append(f"**Explicit Knowledge Packs**: {', '.join(self.explicit_knowledge_packs)}")
        if self.explicit_knowledge_docs:
            lines.append(f"**Explicit Knowledge Docs**: {', '.join(self.explicit_knowledge_docs)}")
        lines.append("")

        for phase in self.phases:
            feedback_tag = " [FEEDBACK GATE]" if phase.feedback_questions else ""
            approval_tag = " [APPROVAL REQUIRED]" if phase.approval_required else ""
            lines.append(f"## Phase {phase.phase_id}: {phase.name}{approval_tag}{feedback_tag}")
            lines.append("")
            if phase.approval_required and phase.approval_description:
                lines.append(f"> {phase.approval_description}")
                lines.append("")
            for step in phase.steps:
                _parallel_tag = " (parallel)" if step.parallel_safe else ""
                if step.team:
                    lines.append(f"### Step {step.step_id}: Team{_parallel_tag}")
                    lines.append(f"- **Task**: {step.task_description}")
                    lines.append(f"- **Members**:")
                    for member in step.team:
                        lines.append(f"  - {member.member_id}: {member.agent_name} ({member.role})")
                        if member.task_description:
                            lines.append(f"    {member.task_description}")
                else:
                    lines.append(f"### Step {step.step_id}: {step.agent_name}{_parallel_tag}")
                    lines.append(f"- **Model**: {step.model}")
                    lines.append(f"- **Task**: {step.task_description}")
                if step.expected_outcome:
                    lines.append(f"- **Expected outcome**: {step.expected_outcome}")
                if step.depends_on:
                    lines.append(f"- **Depends on**: {', '.join(step.depends_on)}")
                if step.deliverables:
                    lines.append(f"- **Deliverables**: {', '.join(step.deliverables)}")
                if step.allowed_paths:
                    lines.append(f"- **Writes to**: {', '.join(step.allowed_paths)}")
                if step.blocked_paths:
                    lines.append(f"- **Blocked from**: {', '.join(step.blocked_paths)}")
                if step.knowledge:
                    lines.append("- **Knowledge**:")
                    for att in step.knowledge:
                        pack_label = f" ({att.pack_name})" if att.pack_name else ""
                        lines.append(
                            f"  - {att.document_name}{pack_label}"
                            f" — {att.delivery} ({att.source})"
                        )
                lines.append("")

            if phase.gate:
                lines.append(f"### Gate: {phase.gate.gate_type}")
                if phase.gate.command:
                    lines.append(f"- **Command**: `{phase.gate.command}`")
                if phase.gate.description:
                    lines.append(f"- {phase.gate.description}")
                lines.append("")

            if phase.feedback_questions:
                lines.append("### Feedback Gate")
                lines.append("")
                for fq in phase.feedback_questions:
                    lines.append(f"**{fq.question_id}**: {fq.question}")
                    if fq.context:
                        lines.append(f"> {fq.context}")
                    for idx, opt in enumerate(fq.options):
                        agent = fq.option_agents[idx] if idx < len(fq.option_agents) else "?"
                        lines.append(f"  - [{idx}] {opt} → *{agent}*")
                    lines.append("")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plan amendments (recorded modifications to the plan during execution)
# ---------------------------------------------------------------------------

@dataclass
class PlanAmendment:
    """A recorded modification to the plan during execution.

    Amendments are created by ``baton execute amend`` when the plan
    needs to be adjusted mid-flight — for example, after a gate fails
    and remediation steps are added, or after human approval with
    feedback.

    Attributes:
        amendment_id: Unique identifier for this amendment.
        trigger: What caused the amendment — ``"gate_feedback"``,
            ``"approval_feedback"``, or ``"manual"``.
        trigger_phase_id: Phase that triggered the amendment.
        description: What was changed and why.
        phases_added: Phase IDs of newly inserted phases.
        steps_added: Step IDs of newly inserted steps.
        created_at: ISO 8601 timestamp.
        feedback: Reviewer or approver feedback that motivated this
            amendment.
    """

    amendment_id: str
    trigger: str                    # "gate_feedback", "approval_feedback", "manual"
    trigger_phase_id: int
    description: str
    phases_added: list[int] = field(default_factory=list)   # phase_ids of new phases
    steps_added: list[str] = field(default_factory=list)    # step_ids of new steps
    created_at: str = ""
    feedback: str = ""              # reviewer/approver feedback that triggered this
    metadata: dict[str, str] = field(default_factory=dict)  # arbitrary key/value context

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "amendment_id": self.amendment_id,
            "trigger": self.trigger,
            "trigger_phase_id": self.trigger_phase_id,
            "description": self.description,
            "phases_added": self.phases_added,
            "steps_added": self.steps_added,
            "created_at": self.created_at,
            "feedback": self.feedback,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> PlanAmendment:
        return cls(
            amendment_id=data.get("amendment_id", ""),
            trigger=data.get("trigger", "manual"),
            trigger_phase_id=data.get("trigger_phase_id", 0),
            description=data.get("description", ""),
            phases_added=data.get("phases_added", []),
            steps_added=data.get("steps_added", []),
            created_at=data.get("created_at", ""),
            feedback=data.get("feedback", ""),
            metadata=data.get("metadata", {}),
        )


# ---------------------------------------------------------------------------
# Execution State (persisted between CLI calls)
# ---------------------------------------------------------------------------

@dataclass
class TeamStepResult:
    """Result of a single team member's work within a team step.

    Collected individually per member and aggregated into the parent
    ``StepResult.member_results`` list.

    Attributes:
        member_id: Matches ``TeamMember.member_id``.
        agent_name: Agent that executed this member role.
        status: ``"complete"`` or ``"failed"``.
        outcome: Free-text summary of the member's work.
        files_changed: Files the member created or modified.
    """

    member_id: str
    agent_name: str
    status: str = "complete"        # complete, failed
    outcome: str = ""
    files_changed: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "member_id": self.member_id,
            "agent_name": self.agent_name,
            "status": self.status,
            "outcome": self.outcome,
            "files_changed": self.files_changed,
        }

    @classmethod
    def from_dict(cls, data: dict) -> TeamStepResult:
        return cls(
            member_id=data.get("member_id", ""),
            agent_name=data.get("agent_name", ""),
            status=data.get("status", "complete"),
            outcome=data.get("outcome", ""),
            files_changed=data.get("files_changed", []),
        )


@dataclass
class StepResult:
    """Outcome of a single step execution.

    Recorded by ``baton execute record`` after each agent dispatch
    completes or fails.  Stored in ``ExecutionState.step_results``
    and used by the executor to determine the next action.

    Attributes:
        step_id: Matches ``PlanStep.step_id``.
        agent_name: Agent that executed this step.
        status: ``"complete"``, ``"failed"``, or ``"dispatched"``
            (in-progress).
        outcome: Free-text summary of what the agent accomplished.
        files_changed: Filesystem paths created or modified.
        commit_hash: Git commit SHA for this step's work.
        estimated_tokens: Estimated token consumption (real if session
            data available; char/4 heuristic otherwise).
        input_tokens: Sum of input_tokens across all assistant turns in
            the session window for this step.  0 when real data is
            unavailable (legacy or pre-session-scan steps).
        cache_read_tokens: Sum of cache_read_input_tokens for this step.
        cache_creation_tokens: Sum of cache_creation_input_tokens for
            this step.
        output_tokens: Sum of output_tokens for this step.
        model_id: Exact model string (e.g. ``"claude-opus-4-7"``) from
            the most common non-synthetic model observed in the session
            window.  Empty when real data is unavailable.
        session_id: Claude Code session UUID used to source the real
            token counts.  Set at ``mark_dispatched`` time from
            ``$CLAUDE_SESSION_ID``.  Empty when not available.
        step_started_at: ISO 8601 timestamp set when the step is
            dispatched.  Used as the lower bound when scanning the
            session JSONL for this step's token data.
        duration_seconds: Wall-clock execution time.
        retries: Number of retry attempts.
        error: Error message if the step failed.
        completed_at: ISO 8601 completion timestamp.
        member_results: Per-member results for team steps.
        deviations: Plan deviations reported by the agent during
            execution.
    """

    step_id: str
    agent_name: str
    status: str = "complete"        # complete, failed, dispatched
    outcome: str = ""               # free-text summary
    files_changed: list[str] = field(default_factory=list)
    commit_hash: str = ""
    estimated_tokens: int = 0
    # Real per-step token fields (populated by session JSONL scanner).
    # All default to 0/"" so existing states deserialize without error.
    input_tokens: int = 0
    cache_read_tokens: int = 0
    cache_creation_tokens: int = 0
    output_tokens: int = 0
    model_id: str = ""
    session_id: str = ""
    step_started_at: str = ""
    duration_seconds: float = 0.0
    retries: int = 0
    error: str = ""
    completed_at: str = ""
    member_results: list[TeamStepResult] = field(default_factory=list)  # team step results
    deviations: list[str] = field(default_factory=list)  # plan deviations reported by agent
    interaction_history: list[InteractionTurn] = field(default_factory=list)  # multi-turn exchange
    step_type: str = "developing"   # echoed from PlanStep for analytics/queries
    updated_at: str = ""            # ISO 8601 UTC; set on every status mutation; used for bi-directional split-brain reconciliation
    outcome_spillover_path: str = ""  # relative path under execution dir to FULL outcome when truncated

    def to_dict(self) -> dict:
        d = {
            "step_id": self.step_id,
            "agent_name": self.agent_name,
            "status": self.status,
            "outcome": self.outcome,
            "files_changed": self.files_changed,
            "commit_hash": self.commit_hash,
            "estimated_tokens": self.estimated_tokens,
            "input_tokens": self.input_tokens,
            "cache_read_tokens": self.cache_read_tokens,
            "cache_creation_tokens": self.cache_creation_tokens,
            "output_tokens": self.output_tokens,
            "model_id": self.model_id,
            "session_id": self.session_id,
            "step_started_at": self.step_started_at,
            "duration_seconds": self.duration_seconds,
            "retries": self.retries,
            "error": self.error,
            "completed_at": self.completed_at,
            "deviations": self.deviations,
            "step_type": self.step_type,
            "updated_at": self.updated_at,
            "outcome_spillover_path": self.outcome_spillover_path,
        }
        if self.member_results:
            d["member_results"] = [m.to_dict() for m in self.member_results]
        if self.interaction_history:
            d["interaction_history"] = [t.to_dict() for t in self.interaction_history]
        return d

    @classmethod
    def from_dict(cls, data: dict) -> StepResult:
        data = dict(data)  # don't mutate caller's dict
        member_results = [
            TeamStepResult.from_dict(m) for m in data.pop("member_results", [])
        ]
        # Extract deviations before passing remaining fields to __init__
        deviations = data.pop("deviations", [])
        # Extract interaction_history before passing remaining fields to __init__
        interaction_history = [
            InteractionTurn.from_dict(t) for t in data.pop("interaction_history", [])
        ]
        obj = cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})
        obj.member_results = member_results
        obj.deviations = deviations
        obj.interaction_history = interaction_history
        return obj


@dataclass
class ApprovalResult:
    """Outcome of a human approval checkpoint.

    Recorded by ``baton execute approve`` when a phase with
    ``approval_required=True`` reaches the approval gate.

    Attributes:
        phase_id: Phase that required approval.
        result: Decision — ``"approve"``, ``"reject"``, or
            ``"approve-with-feedback"`` (which inserts a remediation
            phase via plan amendment).
        feedback: Optional feedback from the reviewer.
        decided_at: ISO 8601 timestamp of the decision.
        decision_source: How this approval was decided — ``"human"``,
            ``"daemon_auto"``, ``"api"``, or ``"policy_auto"`` (A2).
        actor: Best-available identity of the approver —
            ``"$USER@$HOSTNAME"`` for CLI, ``"daemon"`` for auto (A2).
        rationale: Optional structured rationale for the decision (A2).
            Complements ``feedback`` with machine-readable context.
    """

    phase_id: int
    result: str                     # "approve", "reject", "approve-with-feedback"
    feedback: str = ""
    decided_at: str = ""
    decision_source: str = ""       # A2: human | daemon_auto | api | policy_auto
    actor: str = ""                 # A2: $USER@$HOSTNAME or "daemon"
    rationale: str = ""             # A2: structured rationale

    def __post_init__(self) -> None:
        if not self.decided_at:
            self.decided_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "phase_id": self.phase_id,
            "result": self.result,
            "feedback": self.feedback,
            "decided_at": self.decided_at,
            "decision_source": self.decision_source,
            "actor": self.actor,
            "rationale": self.rationale,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ApprovalResult:
        return cls(
            phase_id=data.get("phase_id", 0),
            result=data.get("result", "approve"),
            feedback=data.get("feedback", ""),
            decided_at=data.get("decided_at", ""),
            decision_source=data.get("decision_source", ""),
            actor=data.get("actor", ""),
            rationale=data.get("rationale", ""),
        )


@dataclass
class FeedbackQuestion:
    """A multiple-choice question presented during a feedback gate.

    Feedback gates present 1-4 focused questions to the user after
    initial planning and research phases complete.  Each answer maps
    to an agent and prompt that will be dispatched immediately,
    enabling high-throughput user steering of large changes.

    Attributes:
        question_id: Unique identifier within the feedback set.
        question: The question text shown to the user.
        context: Background explaining why this choice matters.
        options: Available choices (2-6 items).
        option_agents: Parallel list — agent name to dispatch for
            each option.
        option_prompts: Parallel list — delegation prompt template
            for each option.  ``{task}`` is replaced with the plan's
            ``task_summary`` at dispatch time.
    """

    question_id: str
    question: str
    context: str = ""
    options: list[str] = field(default_factory=list)
    option_agents: list[str] = field(default_factory=list)
    option_prompts: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "question_id": self.question_id,
            "question": self.question,
            "context": self.context,
            "options": self.options,
            "option_agents": self.option_agents,
            "option_prompts": self.option_prompts,
        }

    @classmethod
    def from_dict(cls, data: dict) -> FeedbackQuestion:
        return cls(
            question_id=data.get("question_id", ""),
            question=data.get("question", ""),
            context=data.get("context", ""),
            options=data.get("options", []),
            option_agents=data.get("option_agents", []),
            option_prompts=data.get("option_prompts", []),
        )


@dataclass
class FeedbackResult:
    """Outcome of a user's answer to a feedback question.

    When the user selects an option, the engine maps the choice to an
    agent and prompt, then amends the plan with a new dispatch step.

    Attributes:
        phase_id: Phase that presented the feedback gate.
        question_id: Which question was answered.
        chosen_option: The selected option text.
        chosen_index: Zero-based index into the options list.
        dispatched_step_id: Step ID created for the resulting dispatch.
        decided_at: ISO 8601 timestamp of the decision.
    """

    phase_id: int
    question_id: str
    chosen_option: str
    chosen_index: int
    dispatched_step_id: str = ""
    decided_at: str = ""

    def __post_init__(self) -> None:
        if not self.decided_at:
            self.decided_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "phase_id": self.phase_id,
            "question_id": self.question_id,
            "chosen_option": self.chosen_option,
            "chosen_index": self.chosen_index,
            "dispatched_step_id": self.dispatched_step_id,
            "decided_at": self.decided_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> FeedbackResult:
        return cls(
            phase_id=data.get("phase_id", 0),
            question_id=data.get("question_id", ""),
            chosen_option=data.get("chosen_option", ""),
            chosen_index=data.get("chosen_index", 0),
            dispatched_step_id=data.get("dispatched_step_id", ""),
            decided_at=data.get("decided_at", ""),
        )


@dataclass
class GateResult:
    """Outcome of a QA gate check.

    Recorded by ``baton execute gate`` after running the gate command
    and evaluating the result.

    Attributes:
        phase_id: Phase whose gate was checked.
        gate_type: Gate category (matches ``PlanGate.gate_type``).
        passed: Whether the gate check succeeded.
        output: Command stdout/stderr or reviewer notes.
        checked_at: ISO 8601 timestamp of the check.
        command: The shell command that was executed (A6 traceability).
        exit_code: Subprocess exit code, or ``None`` for manual gates (A6).
        decision_source: How this gate was decided — ``"human"``,
            ``"daemon_auto"``, ``"api"``, or ``"policy_auto"`` (A2).
        actor: Best-available identity of who triggered this gate —
            ``"$USER@$HOSTNAME"`` for CLI, ``"daemon"`` for auto (A2).
    """

    phase_id: int
    gate_type: str
    passed: bool
    output: str = ""                # command output or reviewer notes
    checked_at: str = ""
    command: str = ""               # A6: the command that was run
    exit_code: int | None = None    # A6: subprocess exit code (None = manual)
    decision_source: str = ""       # A2: human | daemon_auto | api | policy_auto
    actor: str = ""                 # A2: $USER@$HOSTNAME or "daemon"

    def to_dict(self) -> dict:
        return {
            "phase_id": self.phase_id,
            "gate_type": self.gate_type,
            "passed": self.passed,
            "output": self.output,
            "checked_at": self.checked_at,
            "command": self.command,
            "exit_code": self.exit_code,
            "decision_source": self.decision_source,
            "actor": self.actor,
        }

    @classmethod
    def from_dict(cls, data: dict) -> GateResult:
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# Consolidation models (cherry-pick rebase of agent commits)
# ---------------------------------------------------------------------------

@dataclass
class FileAttribution:
    """Per-file change attribution to a specific step.

    Populated by ``CommitConsolidator._diff_stats()`` after each
    cherry-pick and stored in ``ConsolidationResult.attributions``.

    Attributes:
        file_path: Repository-relative path of the changed file.
        step_id: Step that produced this change.
        agent_name: Agent that executed the step.
        insertions: Lines added.
        deletions: Lines removed.
    """

    file_path: str
    step_id: str
    agent_name: str
    insertions: int = 0
    deletions: int = 0

    def to_dict(self) -> dict:
        return {
            "file_path": self.file_path,
            "step_id": self.step_id,
            "agent_name": self.agent_name,
            "insertions": self.insertions,
            "deletions": self.deletions,
        }

    @classmethod
    def from_dict(cls, data: dict) -> FileAttribution:
        return cls(
            file_path=data.get("file_path", ""),
            step_id=data.get("step_id", ""),
            agent_name=data.get("agent_name", ""),
            insertions=data.get("insertions", 0),
            deletions=data.get("deletions", 0),
        )


@dataclass
class ConsolidationResult:
    """Outcome of rebasing agent commits onto the feature branch.

    Stored on ``ExecutionState.consolidation_result`` after
    ``CommitConsolidator.consolidate()`` completes (or partially
    completes on conflict).

    Attributes:
        status: Overall outcome — ``"success"``, ``"partial"``, or
            ``"conflict"``.
        rebased_commits: Ordered list of dicts with keys ``step_id``,
            ``agent_name``, ``original_hash``, ``new_hash`` — one entry
            per successfully cherry-picked commit.
        final_head: HEAD SHA after consolidation (empty on conflict).
        base_commit: HEAD SHA recorded before the first cherry-pick.
        files_changed: Deduplicated list of all repository-relative paths
            touched across all rebased commits.
        total_insertions: Sum of inserted lines across all rebased commits.
        total_deletions: Sum of deleted lines across all rebased commits.
        attributions: Per-file attribution records linking each change to a
            step and agent.
        conflict_files: Paths that triggered a merge conflict (non-empty
            only when ``status == "conflict"``).
        conflict_step_id: The step whose cherry-pick produced a conflict.
        skipped_steps: Step IDs whose commits had no hash recorded and were
            therefore skipped by the consolidator.
        started_at: ISO 8601 timestamp at consolidation start.
        completed_at: ISO 8601 timestamp at consolidation end.
        error: Exception message if an unexpected error terminated
            consolidation early.
    """

    status: str = "success"          # success | partial | conflict
    rebased_commits: list[dict] = field(default_factory=list)
    final_head: str = ""
    base_commit: str = ""
    files_changed: list[str] = field(default_factory=list)
    total_insertions: int = 0
    total_deletions: int = 0
    attributions: list[FileAttribution] = field(default_factory=list)
    conflict_files: list[str] = field(default_factory=list)
    conflict_step_id: str = ""
    skipped_steps: list[str] = field(default_factory=list)
    started_at: str = ""
    completed_at: str = ""
    error: str = ""

    def to_dict(self) -> dict:
        return {
            "status": self.status,
            "rebased_commits": list(self.rebased_commits),
            "final_head": self.final_head,
            "base_commit": self.base_commit,
            "files_changed": self.files_changed,
            "total_insertions": self.total_insertions,
            "total_deletions": self.total_deletions,
            "attributions": [a.to_dict() for a in self.attributions],
            "conflict_files": self.conflict_files,
            "conflict_step_id": self.conflict_step_id,
            "skipped_steps": self.skipped_steps,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "error": self.error,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ConsolidationResult:
        return cls(
            status=data.get("status", "success"),
            rebased_commits=list(data.get("rebased_commits", [])),
            final_head=data.get("final_head", ""),
            base_commit=data.get("base_commit", ""),
            files_changed=data.get("files_changed", []),
            total_insertions=data.get("total_insertions", 0),
            total_deletions=data.get("total_deletions", 0),
            attributions=[
                FileAttribution.from_dict(a) for a in data.get("attributions", [])
            ],
            conflict_files=data.get("conflict_files", []),
            conflict_step_id=data.get("conflict_step_id", ""),
            skipped_steps=data.get("skipped_steps", []),
            started_at=data.get("started_at", ""),
            completed_at=data.get("completed_at", ""),
            error=data.get("error", ""),
        )


@dataclass
class ExecutionState:
    """Persistent state of a running execution, saved between CLI calls.

    Serialized as ``execution-state.json`` in the execution directory.
    Each ``baton execute`` subcommand reads, modifies, and writes this
    state back.  The executor uses it to determine the next action via
    ``ExecutionAction``.

    Attributes:
        task_id: Unique execution identifier.
        plan: The ``MachinePlan`` being executed (may be amended).
        current_phase: Index into ``plan.phases``.
        current_step_index: Index into the current phase's steps.
        status: Overall execution state — ``"running"``,
            ``"gate_pending"``, ``"approval_pending"``, ``"complete"``,
            or ``"failed"``.
        step_results: Results recorded so far.
        gate_results: Gate check outcomes.
        approval_results: Human approval outcomes.
        amendments: Modifications applied to the plan during execution.
        started_at: ISO 8601 execution start time.
        completed_at: ISO 8601 completion time, if finished.
        pending_gaps: Unresolved knowledge gap signals.
        resolved_decisions: Resolved gaps injected on re-dispatch.
        consolidation_result: Result of the commit consolidation pass run
            at execution completion.  ``None`` when consolidation has not
            yet been attempted or is not applicable.
    """

    task_id: str
    plan: MachinePlan
    current_phase: int = 0              # index into plan.phases
    current_step_index: int = 0         # index into current phase's steps
    status: str = "running"             # running, gate_pending, approval_pending, feedback_pending, complete, failed, cancelled
    step_results: list[StepResult] = field(default_factory=list)
    gate_results: list[GateResult] = field(default_factory=list)
    approval_results: list[ApprovalResult] = field(default_factory=list)
    feedback_results: list[FeedbackResult] = field(default_factory=list)
    amendments: list[PlanAmendment] = field(default_factory=list)
    started_at: str = ""
    completed_at: str = ""
    pending_gaps: list[KnowledgeGapSignal] = field(default_factory=list)
    resolved_decisions: list[ResolvedDecision] = field(default_factory=list)
    # Session-level knowledge deduplication: maps doc key → step_id where
    # it was first delivered inline.  Empty on fresh starts; absent in older
    # state files (graceful default applied in from_dict).
    delivered_knowledge: dict[str, str] = field(default_factory=dict)
    # Populated by CommitConsolidator.consolidate() at execution completion.
    # None until consolidation is attempted; absent in older state files
    # (graceful default applied in from_dict).
    consolidation_result: ConsolidationResult | None = None
    # F0.3 — auditor VETO override (bd-f606).  When True the executor
    # advances past a VETO'd HIGH/CRITICAL phase but appends an Override
    # row to compliance-audit.jsonl via ComplianceChainWriter.
    # Justification is required when force_override=True; the CLI rejects
    # --force without --justification.
    force_override: bool = False
    override_justification: str = ""

    # Wave 1.3 (bd-86bf): Worktree isolation fields.
    # step_worktrees maps step_id -> serialised WorktreeHandle dict.
    # Absent from legacy state files; all accessors use getattr(..., {}).
    step_worktrees: dict[str, dict] = field(default_factory=dict)
    # steps_ran_in_place records steps that degraded to in-place execution
    # because worktree creation failed.  Maps step_id -> reason string.
    # Absent from legacy state files; defaults to empty dict.
    steps_ran_in_place: dict[str, str] = field(default_factory=dict)
    # The git branch that was current when this execution started.
    # Used as base_branch for all worktree create() calls.
    working_branch: str = ""
    # bd-def9: SHA of the rebased tip of working_branch after the most-recent
    # successful fold_back().  Empty until the first fold-back completes.
    working_branch_head: str = ""

    # Wave 5 (bd-e208, bd-1483, bd-9839): Human-Agent Loop fields.
    # All fields use getattr(state, "...", default) in accessors for legacy
    # file load compatibility.
    #
    # bd-e208: Takeover records — active record has empty resumed_at.
    takeover_records: list[dict] = field(default_factory=list)
    # bd-1483: Self-heal attempt records.
    selfheal_attempts: list[dict] = field(default_factory=list)
    # bd-9839: Speculation records — keyed by spec_id.
    speculations: dict[str, dict] = field(default_factory=dict)

    # End-user readiness #7: cumulative USD spent across all subsystems
    # (self-heal, speculation, immune sweeps) for this run.  Persisted so a
    # resumed run picks up counting where it left off rather than resetting
    # to zero and allowing the ceiling to be exceeded.
    # Default 0.0 for legacy state files (getattr guard in all accessors).
    run_cumulative_spend_usd: float = 0.0

    # Scope expansion: queued expansion requests detected during execution.
    # Processed at phase boundaries by _process_pending_expansions().
    pending_scope_expansions: list[dict] = field(default_factory=list)
    scope_expansions_applied: int = 0

    def __post_init__(self) -> None:
        if not self.started_at:
            self.started_at = datetime.now(timezone.utc).isoformat()

    @property
    def current_phase_obj(self) -> PlanPhase | None:
        if 0 <= self.current_phase < len(self.plan.phases):
            return self.plan.phases[self.current_phase]
        return None

    @property
    def completed_step_ids(self) -> set[str]:
        return {r.step_id for r in self.step_results if r.status == "complete"}

    @property
    def failed_step_ids(self) -> set[str]:
        return {r.step_id for r in self.step_results if r.status == "failed"}

    @property
    def dispatched_step_ids(self) -> set[str]:
        return {r.step_id for r in self.step_results if r.status == "dispatched"}

    @property
    def interrupted_step_ids(self) -> set[str]:
        return {r.step_id for r in self.step_results if r.status == "interrupted"}

    def get_step_result(self, step_id: str) -> StepResult | None:
        """Look up the result for a specific step.

        Args:
            step_id: The step ID to search for.

        Returns:
            The matching ``StepResult``, or ``None`` if the step has
            not been recorded yet.
        """
        for r in self.step_results:
            if r.step_id == step_id:
                return r
        return None

    def to_dict(self) -> dict:
        return {
            "task_id": self.task_id,
            "plan": self.plan.to_dict(),
            "current_phase": self.current_phase,
            "current_step_index": self.current_step_index,
            "status": self.status,
            "step_results": [r.to_dict() for r in self.step_results],
            "gate_results": [g.to_dict() for g in self.gate_results],
            "approval_results": [a.to_dict() for a in self.approval_results],
            "feedback_results": [f.to_dict() for f in self.feedback_results],
            "amendments": [a.to_dict() for a in self.amendments],
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "pending_gaps": [g.to_dict() for g in self.pending_gaps],
            "resolved_decisions": [d.to_dict() for d in self.resolved_decisions],
            "delivered_knowledge": dict(self.delivered_knowledge),
            "consolidation_result": (
                self.consolidation_result.to_dict()
                if self.consolidation_result is not None
                else None
            ),
            "force_override": self.force_override,
            "override_justification": self.override_justification,
            # Wave 1.3 (bd-86bf): worktree isolation state
            "step_worktrees": dict(getattr(self, "step_worktrees", {})),
            # steps that degraded to in-place execution after worktree failure
            "steps_ran_in_place": dict(getattr(self, "steps_ran_in_place", {})),
            "working_branch": getattr(self, "working_branch", ""),
            # Wave 5 (bd-e208, bd-1483, bd-9839): Human-Agent Loop state
            "takeover_records": list(getattr(self, "takeover_records", [])),
            "selfheal_attempts": list(getattr(self, "selfheal_attempts", [])),
            "speculations": dict(getattr(self, "speculations", {})),
            # bd-def9: rebased tip SHA after most-recent fold_back()
            "working_branch_head": getattr(self, "working_branch_head", ""),
            # end-user readiness #7: run-level cumulative spend for ceiling tracking
            "run_cumulative_spend_usd": float(getattr(self, "run_cumulative_spend_usd", 0.0)),
            "pending_scope_expansions": list(getattr(self, "pending_scope_expansions", [])),
            "scope_expansions_applied": int(getattr(self, "scope_expansions_applied", 0)),
        }

    @classmethod
    def from_dict(cls, data: dict) -> ExecutionState:
        cr_data = data.get("consolidation_result")
        return cls(
            task_id=data["task_id"],
            plan=MachinePlan.from_dict(data["plan"]),
            current_phase=data.get("current_phase", 0),
            current_step_index=data.get("current_step_index", 0),
            status=data.get("status", "running"),
            step_results=[StepResult.from_dict(r) for r in data.get("step_results", [])],
            gate_results=[GateResult.from_dict(g) for g in data.get("gate_results", [])],
            approval_results=[ApprovalResult.from_dict(a) for a in data.get("approval_results", [])],
            feedback_results=[FeedbackResult.from_dict(f) for f in data.get("feedback_results", [])],
            amendments=[PlanAmendment.from_dict(a) for a in data.get("amendments", [])],
            started_at=data.get("started_at", ""),
            completed_at=data.get("completed_at", ""),
            pending_gaps=[KnowledgeGapSignal.from_dict(g) for g in data.get("pending_gaps", [])],
            resolved_decisions=[ResolvedDecision.from_dict(d) for d in data.get("resolved_decisions", [])],
            delivered_knowledge=dict(data.get("delivered_knowledge", {})),
            consolidation_result=ConsolidationResult.from_dict(cr_data) if cr_data is not None else None,
            force_override=bool(data.get("force_override", False)),
            override_justification=data.get("override_justification", ""),
            # Wave 1.3 (bd-86bf): worktree isolation — default to empty for legacy files
            step_worktrees=dict(data.get("step_worktrees", {})),
            steps_ran_in_place=dict(data.get("steps_ran_in_place", {})),
            working_branch=data.get("working_branch", ""),
            # Wave 5 (bd-e208, bd-1483, bd-9839): default to empty for legacy files
            takeover_records=list(data.get("takeover_records", [])),
            selfheal_attempts=list(data.get("selfheal_attempts", [])),
            speculations=dict(data.get("speculations", {})),
            # bd-def9: getattr guard for legacy state files that predate this field
            working_branch_head=data.get("working_branch_head", ""),
            # end-user readiness #7: default 0.0 for legacy state files
            run_cumulative_spend_usd=float(data.get("run_cumulative_spend_usd", 0.0)),
            pending_scope_expansions=list(data.get("pending_scope_expansions", [])),
            scope_expansions_applied=int(data.get("scope_expansions_applied", 0)),
        )


# ---------------------------------------------------------------------------
# Execution Actions (returned by the engine to tell the caller what to do)
# ---------------------------------------------------------------------------

@dataclass
class ExecutionAction:
    """Instruction from the execution engine to the driving session.

    Returned by ``baton execute next`` to tell the orchestrator what
    to do.  The ``action_type`` determines which fields are populated.
    The CLI's ``_print_action()`` renders this as structured output
    that Claude reads to drive the orchestration loop.

    Attributes:
        action_type: What kind of action is required.
        message: Human-readable description of the action.
        agent_name: Agent to dispatch (``DISPATCH`` only).
        agent_model: Model for the dispatch (``DISPATCH`` only).
        delegation_prompt: Full prompt to send to the agent
            (``DISPATCH`` only).
        step_id: Plan step being dispatched (``DISPATCH`` only).
        path_enforcement: PreToolUse hook command for path sandboxing
            (``DISPATCH`` only).
        gate_type: Gate category (``GATE`` only).
        gate_command: Bash command to run (``GATE`` only).
        phase_id: Phase being gated or approved (``GATE`` / ``APPROVAL``).
        approval_context: Summary for the reviewer (``APPROVAL`` only).
        approval_options: Available approval choices (``APPROVAL`` only).
        summary: Final execution summary (``COMPLETE`` / ``FAILED``).
        parallel_actions: Batch of actions for parallel dispatch.
    """

    action_type: ActionType             # strongly-typed; serialises to str via to_dict()
    message: str = ""                   # human-readable description

    # For DISPATCH actions:
    agent_name: str = ""
    agent_model: str = ""
    delegation_prompt: str = ""
    step_id: str = ""
    step_type: str = ""             # echoed from PlanStep for caller routing
    command: str = ""               # for automation steps
    # Path enforcement hook command (for PreToolUse):
    path_enforcement: str = ""
    # MCP server names to pass through to this dispatch:
    mcp_servers: list[str] = field(default_factory=list)
    # Subagent isolation contract — set to "worktree" when the engine
    # emits this action as part of a parallel DISPATCH wave (>=2 actions).
    # The orchestrator MUST forward this onto the Agent invocation as
    # ``isolation="worktree"`` so concurrent agents land in separate git
    # worktrees and cannot contaminate the parent branch.  Empty string
    # means no isolation contract (singleton or sequential dispatch).
    isolation: str = ""

    # For GATE actions:
    gate_type: str = ""
    gate_command: str = ""
    phase_id: int = 0

    # For APPROVAL actions:
    approval_context: str = ""          # summary of phase output for reviewer
    approval_options: list[str] = field(default_factory=list)

    # For FEEDBACK actions:
    feedback_questions: list[FeedbackQuestion] = field(default_factory=list)
    feedback_context: str = ""          # summary of prior work for context

    # For COMPLETE/FAILED actions:
    summary: str = ""

    # For batch dispatch (parallel steps / team members):
    parallel_actions: list[ExecutionAction] = field(default_factory=list)

    # For INTERACT actions (multi-turn step conversation):
    interact_prompt: str = ""          # current agent output awaiting human response
    interact_step_id: str = ""         # step that is in interacting status
    interact_agent_name: str = ""      # agent involved in the interaction
    interact_turn: int = 0             # current turn number (1-based)
    interact_max_turns: int = 10       # maximum allowed turns for this step
    interactive: bool = False          # True on DISPATCH when the step is interactive

    # Wave 3.1 — behavioral demo statement echoed from PlanStep.expected_outcome
    # so the CLI and the orchestrator can surface it without re-reading plan.json.
    expected_outcome: str = ""         # DISPATCH only; empty when not derived
    # Wave 1.3 (bd-86bf): worktree isolation fields — empty string when no worktree.
    # Populated at mark_dispatched() time, not at next_actions() time.
    worktree_path: str = ""            # absolute path to isolated worktree; "" = no worktree
    worktree_branch: str = ""          # git branch inside the worktree

    def to_dict(self) -> dict[str, Any]:
        # action_type is serialised as a plain string so CLI / Claude output
        # is unaffected by the internal enum representation.
        d: dict[str, Any] = {"action_type": self.action_type.value, "message": self.message}
        if self.action_type == ActionType.DISPATCH:
            is_team_member = bool(_TEAM_MEMBER_ID_RE.match(self.step_id))
            d.update({
                "agent_name": self.agent_name,
                "agent_model": self.agent_model,
                "delegation_prompt": self.delegation_prompt,
                "step_id": self.step_id,
                "step_type": self.step_type,
                "path_enforcement": self.path_enforcement,
                "is_team_member": is_team_member,
                "interactive": self.interactive,
            })
            if is_team_member:
                # Provide the parent step ID so consumers can call team-record
                # without parsing the member ID themselves.
                d["parent_step_id"] = ".".join(self.step_id.split(".")[:2])
            if self.mcp_servers:
                d["mcp_servers"] = self.mcp_servers
            if self.interactive:
                d["interact_max_turns"] = self.interact_max_turns
            if self.command:
                d["command"] = self.command
            if self.isolation:
                d["isolation"] = self.isolation
            if self.expected_outcome:
                d["expected_outcome"] = self.expected_outcome
            # Wave 1.3 (bd-86bf): include worktree fields when populated
            if self.worktree_path:
                d["worktree_path"] = self.worktree_path
            if self.worktree_branch:
                d["worktree_branch"] = self.worktree_branch
        elif self.action_type == ActionType.GATE:
            d.update({
                "gate_type": self.gate_type,
                "gate_command": self.gate_command,
                "phase_id": self.phase_id,
            })
        elif self.action_type == ActionType.APPROVAL:
            d.update({
                "phase_id": self.phase_id,
                "approval_context": self.approval_context,
                "approval_options": self.approval_options,
            })
        elif self.action_type == ActionType.FEEDBACK:
            d.update({
                "phase_id": self.phase_id,
                "feedback_questions": [q.to_dict() for q in self.feedback_questions],
                "feedback_context": self.feedback_context,
            })
        elif self.action_type == ActionType.INTERACT:
            d.update({
                "interact_prompt": self.interact_prompt,
                "interact_step_id": self.interact_step_id,
                "interact_agent_name": self.interact_agent_name,
                "interact_turn": self.interact_turn,
                "interact_max_turns": self.interact_max_turns,
            })
        elif self.action_type in (ActionType.COMPLETE, ActionType.FAILED):
            d["summary"] = self.summary
        if self.parallel_actions:
            d["parallel_actions"] = [a.to_dict() for a in self.parallel_actions]
        return d
