"""Data models for the closed-loop improvement system.

Covers recommendations, experiments, anomalies, trigger configuration,
improvement reports, and top-level improvement configuration.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class RecommendationCategory(Enum):
    """What aspect of the system a recommendation targets."""

    AGENT_PROMPT = "agent_prompt"
    BUDGET_TIER = "budget_tier"
    ROUTING = "routing"
    SEQUENCING = "sequencing"
    GATE_CONFIG = "gate_config"
    ROSTER = "roster"


class RecommendationStatus(Enum):
    """Lifecycle state of an improvement recommendation."""

    PROPOSED = "proposed"
    APPLIED = "applied"
    REJECTED = "rejected"
    ROLLED_BACK = "rolled_back"


class ExperimentStatus(Enum):
    """Lifecycle state of an A/B experiment tracking a recommendation."""

    RUNNING = "running"
    CONCLUDED = "concluded"
    ROLLED_BACK = "rolled_back"


class AnomalySeverity(Enum):
    """Severity tier for detected behavioral anomalies."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# ---------------------------------------------------------------------------
# Recommendation
# ---------------------------------------------------------------------------

@dataclass
class Recommendation:
    """A single improvement recommendation produced by the analysis pipeline.

    Recommendations are generated by the closed-loop improvement system
    after analyzing usage logs, retrospectives, and scoring data.  Low-risk
    recommendations with confidence above the auto-apply threshold are
    applied automatically; others are surfaced for human review.

    Attributes:
        rec_id: Unique recommendation identifier.
        category: Area of the system to change (``RecommendationCategory`` value).
        target: Specific entity to modify (e.g. agent name, task type).
        action: Short verb phrase describing the change.
        description: Human-readable explanation of the recommendation.
        evidence: References to data that supports this recommendation.
        confidence: Confidence score in ``[0.0, 1.0]``.
        risk: Assessed risk of applying the change.
        auto_applicable: Whether this can be applied without human approval.
        proposed_change: Machine-readable specification of the change.
        rollback_spec: Instructions for reverting the change if needed.
        created_at: ISO 8601 creation timestamp.
        status: Current lifecycle state (``RecommendationStatus`` value).
    """

    rec_id: str
    category: str               # RecommendationCategory value
    target: str                 # e.g. agent name, task type, gate name
    action: str                 # short verb phrase: "downgrade budget", "adjust routing"
    description: str            # human-readable explanation
    evidence: list[str] = field(default_factory=list)   # supporting data references
    confidence: float = 0.0     # 0.0 - 1.0
    risk: str = "low"           # "low", "medium", "high"
    auto_applicable: bool = False
    proposed_change: dict = field(default_factory=dict)  # machine-readable change spec
    rollback_spec: dict = field(default_factory=dict)    # how to undo
    created_at: str = ""
    status: str = "proposed"    # RecommendationStatus value

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "rec_id": self.rec_id,
            "category": self.category,
            "target": self.target,
            "action": self.action,
            "description": self.description,
            "evidence": self.evidence,
            "confidence": self.confidence,
            "risk": self.risk,
            "auto_applicable": self.auto_applicable,
            "proposed_change": self.proposed_change,
            "rollback_spec": self.rollback_spec,
            "created_at": self.created_at,
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Recommendation:
        return cls(
            rec_id=data["rec_id"],
            category=data.get("category", ""),
            target=data.get("target", ""),
            action=data.get("action", ""),
            description=data.get("description", ""),
            evidence=data.get("evidence", []),
            confidence=float(data.get("confidence", 0.0)),
            risk=data.get("risk", "low"),
            auto_applicable=bool(data.get("auto_applicable", False)),
            proposed_change=data.get("proposed_change", {}),
            rollback_spec=data.get("rollback_spec", {}),
            created_at=data.get("created_at", ""),
            status=data.get("status", "proposed"),
        )


# ---------------------------------------------------------------------------
# Experiment
# ---------------------------------------------------------------------------

@dataclass
class Experiment:
    """Tracks the real-world outcome of an applied recommendation.

    After a recommendation is applied, an experiment monitors the
    relevant metric over subsequent executions.  Once enough samples
    are collected (or the time limit expires), the experiment concludes
    with a verdict that determines whether to keep or roll back the
    change.

    Attributes:
        experiment_id: Unique experiment identifier.
        recommendation_id: The ``Recommendation.rec_id`` being tested.
        hypothesis: What improvement is expected.
        metric: The metric being tracked (e.g. ``"first_pass_rate"``).
        baseline_value: Metric value before the change was applied.
        target_value: Metric value the change aims to achieve.
        agent_name: Agent under observation, if agent-specific.
        started_at: ISO 8601 timestamp of experiment start.
        min_samples: Minimum data points before concluding.
        max_duration_days: Auto-conclude after this many days.
        status: Lifecycle state (``ExperimentStatus`` value).
        samples: Collected metric values during the experiment.
        result: Verdict — ``"improved"``, ``"degraded"``,
            ``"inconclusive"``, or empty if still running.
    """

    experiment_id: str
    recommendation_id: str
    hypothesis: str
    metric: str                     # e.g. "first_pass_rate", "gate_pass_rate"
    baseline_value: float = 0.0
    target_value: float = 0.0
    agent_name: str = ""
    started_at: str = ""
    min_samples: int = 5
    max_duration_days: int = 14
    status: str = "running"         # ExperimentStatus value
    samples: list[float] = field(default_factory=list)
    result: str = ""                # "improved", "degraded", "inconclusive", ""

    def __post_init__(self) -> None:
        if not self.started_at:
            self.started_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "experiment_id": self.experiment_id,
            "recommendation_id": self.recommendation_id,
            "hypothesis": self.hypothesis,
            "metric": self.metric,
            "baseline_value": self.baseline_value,
            "target_value": self.target_value,
            "agent_name": self.agent_name,
            "started_at": self.started_at,
            "min_samples": self.min_samples,
            "max_duration_days": self.max_duration_days,
            "status": self.status,
            "samples": self.samples,
            "result": self.result,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Experiment:
        return cls(
            experiment_id=data["experiment_id"],
            recommendation_id=data.get("recommendation_id", ""),
            hypothesis=data.get("hypothesis", ""),
            metric=data.get("metric", ""),
            baseline_value=float(data.get("baseline_value", 0.0)),
            target_value=float(data.get("target_value", 0.0)),
            agent_name=data.get("agent_name", ""),
            started_at=data.get("started_at", ""),
            min_samples=int(data.get("min_samples", 5)),
            max_duration_days=int(data.get("max_duration_days", 14)),
            status=data.get("status", "running"),
            samples=data.get("samples", []),
            result=data.get("result", ""),
        )


# ---------------------------------------------------------------------------
# Anomaly
# ---------------------------------------------------------------------------

@dataclass
class Anomaly:
    """A detected anomaly in agent or system behavior.

    Anomalies are surfaced by the improvement analysis pipeline when a
    metric exceeds its configured threshold.  They may trigger
    ``Recommendation`` generation or be reported for manual review.

    Attributes:
        anomaly_type: Classification of the anomaly (e.g.
            ``"high_failure_rate"``, ``"budget_overrun"``, ``"retry_spike"``).
        severity: Impact level (``AnomalySeverity`` value).
        agent_name: Affected agent, if agent-specific.
        metric: The metric that triggered detection.
        current_value: Observed metric value.
        threshold: Threshold that was exceeded.
        sample_size: Number of data points in the detection window.
        evidence: References to supporting data (task IDs, log entries).
    """

    anomaly_type: str           # e.g. "high_failure_rate", "budget_overrun", "retry_spike"
    severity: str               # AnomalySeverity value
    agent_name: str = ""
    metric: str = ""
    current_value: float = 0.0
    threshold: float = 0.0
    sample_size: int = 0
    evidence: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "anomaly_type": self.anomaly_type,
            "severity": self.severity,
            "agent_name": self.agent_name,
            "metric": self.metric,
            "current_value": self.current_value,
            "threshold": self.threshold,
            "sample_size": self.sample_size,
            "evidence": self.evidence,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Anomaly:
        return cls(
            anomaly_type=data.get("anomaly_type", ""),
            severity=data.get("severity", "low"),
            agent_name=data.get("agent_name", ""),
            metric=data.get("metric", ""),
            current_value=float(data.get("current_value", 0.0)),
            threshold=float(data.get("threshold", 0.0)),
            sample_size=int(data.get("sample_size", 0)),
            evidence=data.get("evidence", []),
        )


# ---------------------------------------------------------------------------
# TriggerConfig
# ---------------------------------------------------------------------------

@dataclass
class TriggerConfig:
    """Configuration for when to trigger improvement analysis.

    Controls the cadence and sensitivity of the closed-loop improvement
    system.  Thresholds are compared against rolling-window metrics
    computed from usage logs.

    Attributes:
        min_tasks_before_analysis: Minimum completed tasks before the
            first analysis runs.
        analysis_interval_tasks: Re-analyze every N new tasks.
        agent_failure_threshold: Agent failure rate that triggers an anomaly.
        gate_failure_threshold: Gate failure rate that triggers an anomaly.
        budget_deviation_threshold: Fractional deviation from budget tier
            that triggers a recommendation.
        confidence_threshold: Minimum confidence for auto-applying a
            recommendation.
        learning_cycle_count_threshold: Number of completed executions since
            the last learning cycle before flagging that a cycle is due.
            Controlled by the ``LEARNING_TRIGGER_COUNT`` env var.
            Default 10.  Set to 0 to disable the counter-based flag.
    """

    min_tasks_before_analysis: int = 3
    analysis_interval_tasks: int = 3
    agent_failure_threshold: float = 0.3
    gate_failure_threshold: float = 0.2
    budget_deviation_threshold: float = 0.5
    confidence_threshold: float = 0.7
    learning_cycle_count_threshold: int = 10

    def to_dict(self) -> dict:
        return {
            "min_tasks_before_analysis": self.min_tasks_before_analysis,
            "analysis_interval_tasks": self.analysis_interval_tasks,
            "agent_failure_threshold": self.agent_failure_threshold,
            "gate_failure_threshold": self.gate_failure_threshold,
            "budget_deviation_threshold": self.budget_deviation_threshold,
            "confidence_threshold": self.confidence_threshold,
            "learning_cycle_count_threshold": self.learning_cycle_count_threshold,
        }

    @classmethod
    def from_dict(cls, data: dict) -> TriggerConfig:
        return cls(
            min_tasks_before_analysis=int(data.get("min_tasks_before_analysis", 3)),
            analysis_interval_tasks=int(data.get("analysis_interval_tasks", 3)),
            agent_failure_threshold=float(data.get("agent_failure_threshold", 0.3)),
            gate_failure_threshold=float(data.get("gate_failure_threshold", 0.2)),
            budget_deviation_threshold=float(data.get("budget_deviation_threshold", 0.5)),
            confidence_threshold=float(data.get("confidence_threshold", 0.7)),
            learning_cycle_count_threshold=int(
                data.get("learning_cycle_count_threshold", 10)
            ),
        )

    @classmethod
    def from_env(cls) -> TriggerConfig:
        """Build a :class:`TriggerConfig` with values from environment variables.

        Reads the following env vars (all optional; falls back to the class
        defaults when absent or non-numeric):

        * ``BATON_MIN_TASKS`` — ``min_tasks_before_analysis`` (int, default 3).
        * ``BATON_ANALYSIS_INTERVAL`` — ``analysis_interval_tasks`` (int, default 3).
        * ``LEARNING_TRIGGER_COUNT`` — ``learning_cycle_count_threshold`` (int,
          default 10).  Set to 0 to disable the counter-based learning cycle flag.

        Other thresholds (failure rates, budget deviation, confidence) are not
        overridable via env vars because they are anomaly-detection knobs rather
        than cadence controls, and mis-setting them via env can silently suppress
        important signals.

        Returns:
            A :class:`TriggerConfig` populated from env vars where present.
        """
        def _int(key: str, default: int) -> int:
            raw = os.environ.get(key, "").strip()
            if raw:
                try:
                    val = int(raw)
                    if val >= 0:
                        return val
                except ValueError:
                    pass
            return default

        return cls(
            min_tasks_before_analysis=_int("BATON_MIN_TASKS", 3),
            analysis_interval_tasks=_int("BATON_ANALYSIS_INTERVAL", 3),
            learning_cycle_count_threshold=_int("LEARNING_TRIGGER_COUNT", 10),
        )


# ---------------------------------------------------------------------------
# ImprovementReport
# ---------------------------------------------------------------------------

@dataclass
class ImprovementReport:
    """Summary of a single improvement analysis cycle.

    Produced after each analysis run and persisted to the improvement
    log.  Contains the anomalies detected, recommendations generated,
    and actions taken (auto-applied or escalated for review).

    Attributes:
        report_id: Unique report identifier.
        timestamp: ISO 8601 timestamp of the analysis run.
        skipped: ``True`` if the analysis was skipped (e.g. insufficient data).
        reason: Explanation for why the analysis was skipped.
        anomalies: Serialized ``Anomaly`` instances found.
        recommendations: Serialized ``Recommendation`` instances generated.
        auto_applied: ``rec_id`` values of recommendations that were
            automatically applied.
        escalated: ``rec_id`` values of recommendations escalated for
            human review.
        active_experiments: ``experiment_id`` values of experiments
            currently running.
    """

    report_id: str
    timestamp: str = ""
    skipped: bool = False
    reason: str = ""            # why skipped, if applicable
    anomalies: list[dict] = field(default_factory=list)     # list of Anomaly.to_dict()
    recommendations: list[dict] = field(default_factory=list)  # list of Recommendation.to_dict()
    auto_applied: list[str] = field(default_factory=list)   # rec_ids that were auto-applied
    escalated: list[str] = field(default_factory=list)      # rec_ids that were escalated
    active_experiments: list[str] = field(default_factory=list)  # experiment_ids

    def __post_init__(self) -> None:
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def to_dict(self) -> dict:
        return {
            "report_id": self.report_id,
            "timestamp": self.timestamp,
            "skipped": self.skipped,
            "reason": self.reason,
            "anomalies": self.anomalies,
            "recommendations": self.recommendations,
            "auto_applied": self.auto_applied,
            "escalated": self.escalated,
            "active_experiments": self.active_experiments,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ImprovementReport:
        return cls(
            report_id=data["report_id"],
            timestamp=data.get("timestamp", ""),
            skipped=bool(data.get("skipped", False)),
            reason=data.get("reason", ""),
            anomalies=data.get("anomalies", []),
            recommendations=data.get("recommendations", []),
            auto_applied=data.get("auto_applied", []),
            escalated=data.get("escalated", []),
            active_experiments=data.get("active_experiments", []),
        )


# ---------------------------------------------------------------------------
# ImprovementConfig
# ---------------------------------------------------------------------------

@dataclass
class ImprovementConfig:
    """Top-level configuration for the closed-loop improvement system.

    Attributes:
        auto_apply_threshold: Minimum confidence score for a
            recommendation to be applied without human approval.
        paused: Circuit breaker — when ``True``, no recommendations
            are applied regardless of confidence.
    """

    auto_apply_threshold: float = 0.8
    paused: bool = False        # circuit breaker state

    def to_dict(self) -> dict:
        return {
            "auto_apply_threshold": self.auto_apply_threshold,
            "paused": self.paused,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ImprovementConfig:
        return cls(
            auto_apply_threshold=float(data.get("auto_apply_threshold", 0.8)),
            paused=bool(data.get("paused", False)),
        )
