"""Behavioural tests for the PreToolUse write guards.

Two guards are covered, both of which are shipped as shell command strings
that Claude Code runs as ``PreToolUse`` hooks:

1. The secret guard wired into ``templates/settings.json`` (installed into
   every user project by ``baton install``).
2. The per-step guard produced by
   ``PromptDispatcher.build_path_enforcement()`` from a step's
   ``allowed_paths`` / ``blocked_paths``.

The tests execute the *real* command strings — extracted from the template
JSON / generated by the dispatcher, never hand-copied — and feed the tool
call through the channel the hook runtime actually uses: a PreToolUse JSON
payload on stdin.  Nothing here inspects source text; the assertions are on
the observable verdict (deny vs allow).

Claude Code hook protocol reminder: exit code 2 denies the tool call, and a
``permissionDecision: "deny"`` object on stdout denies it too.  Any other
non-zero exit is a *non-blocking* error, so 127 ("command not found") is
deliberately NOT treated as a deny.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

from agent_baton.core.engine.dispatcher import PromptDispatcher
from agent_baton.models.execution import PlanStep
from tests._subprocess_helpers import cli_subprocess_env


ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_SETTINGS = ROOT / "templates" / "settings.json"

#: Claude Code denies the tool call on this exit code and no other.
DENY_EXIT_CODE = 2


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _matching_hook_commands(event: str, tool_name: str) -> list[str]:
    """Return every hook command in the template registered for ``tool_name``.

    Mirrors Claude Code's dispatch: an entry with no ``matcher`` applies to
    every tool, otherwise the matcher is a regex tested against the tool name.
    """
    settings = json.loads(TEMPLATE_SETTINGS.read_text(encoding="utf-8"))
    commands: list[str] = []
    for entry in settings.get("hooks", {}).get(event, []):
        matcher = entry.get("matcher")
        if matcher and not re.search(matcher, tool_name):
            continue
        for hook in entry.get("hooks", []):
            command = hook.get("command", "")
            if hook.get("type") == "command" and command:
                commands.append(command)
    return commands


def _pretooluse_payload(
    *,
    tool_name: str = "Write",
    file_path: str | None = None,
    tool_input: dict | None = None,
) -> str:
    """Build a PreToolUse stdin payload in the shape the runtime sends."""
    payload_input: dict = dict(tool_input) if tool_input is not None else {}
    if file_path is not None:
        payload_input["file_path"] = file_path
    payload_input.setdefault("content", "SECRET=1\n")
    return json.dumps(
        {
            "session_id": "test-session",
            "transcript_path": "/dev/null",
            "hook_event_name": "PreToolUse",
            "tool_name": tool_name,
            "tool_input": payload_input,
        }
    )


def _runnable(command: str) -> str:
    """Make a hook command runnable without relying on an installed console script."""
    if command.startswith("baton "):
        return f'"{sys.executable}" -m agent_baton.cli.main ' + command[len("baton "):]
    return command


def _run_hook(command: str, payload: str, cwd: Path) -> subprocess.CompletedProcess:
    env = cli_subprocess_env()
    # The hook runtime does not export the tool input as an environment
    # variable — stdin is the interface.  Guarantee the variable is absent so
    # a guard reading it cannot accidentally succeed here.
    env.pop("CLAUDE_TOOL_INPUT_FILE_PATH", None)
    return subprocess.run(
        _runnable(command),
        shell=True,
        input=payload,
        capture_output=True,
        text=True,
        cwd=str(cwd),
        env=env,
        timeout=60,
    )


def _is_deny(result: subprocess.CompletedProcess) -> bool:
    if result.returncode == DENY_EXIT_CODE:
        return True
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            decoded = json.loads(line)
        except json.JSONDecodeError:
            continue
        specific = decoded.get("hookSpecificOutput") or {}
        if specific.get("permissionDecision") == "deny":
            return True
        if decoded.get("decision") == "block":
            return True
    return False


def _template_verdict(payload: str, cwd: Path, tool_name: str = "Write") -> tuple[bool, str]:
    """Run the template's PreToolUse chain; return (denied, diagnostics)."""
    commands = _matching_hook_commands("PreToolUse", tool_name)
    assert commands, f"templates/settings.json registers no PreToolUse hook for {tool_name}"

    report: list[str] = []
    denied = False
    for command in commands:
        result = _run_hook(command, payload, cwd)
        hook_denied = _is_deny(result)
        denied = denied or hook_denied
        report.append(
            f"  hook: {command[:120]}\n"
            f"    rc={result.returncode} deny={hook_denied} "
            f"stdout={result.stdout.strip()[:200]!r} stderr={result.stderr.strip()[:200]!r}"
        )
    return denied, "\n".join(report)


def _inline_guard_commands(tool_name: str = "Write") -> list[str]:
    """PreToolUse guards that decide on their own, i.e. not the ``baton`` CLI.

    These are the self-contained shell guards shipped in the template.  If a
    future fix deletes them and relies solely on ``baton policy-check``, this
    list is empty and the inline-guard tests below simply do not apply — the
    chain-level tests still hold the line.
    """
    return [
        command
        for command in _matching_hook_commands("PreToolUse", tool_name)
        if not command.startswith("baton ")
    ]


def _step_guard(**kwargs) -> str:
    step = PlanStep(
        step_id="1.1",
        agent_name="backend-engineer",
        task_description="do work",
        **kwargs,
    )
    guard = PromptDispatcher.build_path_enforcement(step)
    assert guard is not None
    return guard


# ---------------------------------------------------------------------------
# templates/settings.json — the shipped secret guard
# ---------------------------------------------------------------------------

class TestTemplateSecretGuard:
    """The installed PreToolUse chain must deny writes to protected paths."""

    PROTECTED_PATHS = [
        ".env",
        "/home/user/project/.env",
        "config/.env",
        "secrets/creds.txt",
        "/srv/app/secrets/creds.txt",
        "/p/.credentials",
        "key.pem",
        "certs/id_rsa.key",
        "node_modules/left-pad/index.js",
    ]

    ALLOWED_PATHS = [
        "src/app.py",
        "src/environment.py",
        "src/keyboard.py",
        "docs/secrets-policy.md",
        "tests/test_env.py",
    ]

    @pytest.mark.parametrize("file_path", PROTECTED_PATHS)
    def test_write_to_protected_path_is_denied(
        self, file_path: str, tmp_path: Path
    ) -> None:
        payload = _pretooluse_payload(file_path=file_path)
        denied, report = _template_verdict(payload, tmp_path)
        assert denied, (
            f"Write to protected path {file_path!r} was ALLOWED by the "
            f"PreToolUse chain in templates/settings.json:\n{report}"
        )

    @pytest.mark.parametrize("file_path", ALLOWED_PATHS)
    def test_write_to_ordinary_path_is_allowed(
        self, file_path: str, tmp_path: Path
    ) -> None:
        payload = _pretooluse_payload(file_path=file_path)
        denied, report = _template_verdict(payload, tmp_path)
        assert not denied, (
            f"Write to ordinary path {file_path!r} was DENIED by the "
            f"PreToolUse chain in templates/settings.json:\n{report}"
        )

    def test_edit_of_protected_path_is_denied(self, tmp_path: Path) -> None:
        """The guard covers Edit, not just Write."""
        payload = _pretooluse_payload(tool_name="Edit", file_path="/home/user/app/.env")
        denied, report = _template_verdict(payload, tmp_path, tool_name="Edit")
        assert denied, f"Edit of .env was ALLOWED:\n{report}"

    def test_unresolvable_file_path_fails_closed(self, tmp_path: Path) -> None:
        """If the payload shape changes, the guard must deny rather than allow.

        Here the file path is present but under an unrecognised key, i.e. the
        guard cannot resolve the target.  Silently exiting 0 in that case is
        what makes an interface change (env var vs stdin, renamed field) a
        silent security regression.
        """
        payload = _pretooluse_payload(
            tool_input={"filePath": "/home/user/project/.env"}
        )
        denied, report = _template_verdict(payload, tmp_path)
        assert denied, (
            "A Write payload whose file path could not be resolved was "
            f"ALLOWED — the guard fails open:\n{report}"
        )


#: Stable ids so a fix that rewrites the guard does not rename the test.
_INLINE_GUARDS = _inline_guard_commands()
_INLINE_GUARD_IDS = [f"inline-guard-{i}" for i in range(len(_INLINE_GUARDS))]


class TestInlineSecretGuardIsLive:
    """Each self-contained shell guard in the template must actually enforce.

    The chain-level tests above can be satisfied by ``baton policy-check``
    alone, which hides a shipped inline guard that never fires.  These tests
    exercise the inline guard on its own so a dead one cannot hide behind a
    working neighbour.
    """

    @pytest.mark.parametrize("command", _INLINE_GUARDS, ids=_INLINE_GUARD_IDS)
    def test_inline_guard_denies_env_write(self, command: str, tmp_path: Path) -> None:
        for file_path in (".env", "/home/user/project/.env", "secrets/creds.txt"):
            result = _run_hook(
                command, _pretooluse_payload(file_path=file_path), tmp_path
            )
            assert _is_deny(result), (
                f"inline PreToolUse guard allowed a write to {file_path!r}: "
                f"rc={result.returncode} stderr={result.stderr.strip()!r}\n"
                f"guard: {command}"
            )

    @pytest.mark.parametrize("command", _INLINE_GUARDS, ids=_INLINE_GUARD_IDS)
    def test_inline_guard_allows_ordinary_write(
        self, command: str, tmp_path: Path
    ) -> None:
        result = _run_hook(
            command, _pretooluse_payload(file_path="src/app.py"), tmp_path
        )
        assert not _is_deny(result), (
            "inline PreToolUse guard denied an ordinary source write: "
            f"rc={result.returncode} stderr={result.stderr.strip()!r}\n"
            f"guard: {command}"
        )


# ---------------------------------------------------------------------------
# PromptDispatcher.build_path_enforcement — per-step guard
# ---------------------------------------------------------------------------

class TestStepPathEnforcementGuard:
    """The generated per-step guard must enforce allowed/blocked paths."""

    def test_blocked_path_is_denied(self, tmp_path: Path) -> None:
        guard = _step_guard(blocked_paths=["secrets/"])
        result = _run_hook(
            guard, _pretooluse_payload(file_path="secrets/creds.txt"), tmp_path
        )
        assert result.returncode == DENY_EXIT_CODE, (
            "write to a blocked_paths entry was not denied: "
            f"rc={result.returncode} stderr={result.stderr.strip()!r}"
        )

    def test_path_outside_allowed_paths_is_denied(self, tmp_path: Path) -> None:
        guard = _step_guard(allowed_paths=["src/"])
        result = _run_hook(
            guard, _pretooluse_payload(file_path="docs/design.md"), tmp_path
        )
        assert result.returncode == DENY_EXIT_CODE, (
            "write outside allowed_paths was not denied: "
            f"rc={result.returncode} stderr={result.stderr.strip()!r}"
        )

    def test_path_inside_allowed_paths_is_permitted(self, tmp_path: Path) -> None:
        guard = _step_guard(allowed_paths=["src/"])
        result = _run_hook(
            guard, _pretooluse_payload(file_path="src/app.py"), tmp_path
        )
        assert result.returncode == 0, (
            "write inside allowed_paths was denied: "
            f"rc={result.returncode} stderr={result.stderr.strip()!r}"
        )
